### PR TITLE
Added: First argument of {% script %} and {% style %} tags now can be…

### PR DESCRIPTION
**Pull request by mt0erfztxt**
… a name of context parameter

### CODE REVIEW

**Comment by mt0erfztxt** [comment]
TravisCI confused on `lein2` command:
> ...
> $ lein2 version
> No command 'lein2' found, did you mean:
> Command 'lein' from package 'leiningen' (universe)
> lein2: command not found
> ...

**Comment by yogthos** [comment]
Hmm wonder what changed there, the current build is passing with the same config. Can try switching to `lein` in `.travis.yml`.

**Comment by yogthos** [comment]
PR itself looks great though, thanks for updating the docs and tests as well. :)

**Comment by yogthos** [comment]
Just pushed out the new version to Clojars, thanks for the help.

**Comment by mt0erfztxt** [comment]
Thanks for updating Clojars artifact so soon. Does I need to close PR and delete branch?

**Comment by yogthos** [comment]
No problem 👍

**Pull request merged**
