### PR TITLE
Catch exceptions, especially out of range exceptions

### PR DESCRIPTION
**Pull request by stw**
Sorry about this, didn't realize subs threw an exception on out of bounds. This should solve that issue.

Thanks,
Steve

### CODE REVIEW

**Comment by yogthos** [comment]
I'm not sure eating the exception silently is the right thing to do here. This could result in unexpected outputs, I think it's best to let the user know that the range was wrong.

**Comment by stw** [comment]
My typical use case is when looping through strings in a table where some may be too long and some are short. I'm thinking that just returning the original string on exception shouldn't be too unexpected, but maybe I'm not thinking of all the use cases?

**Comment by ricardojmendez** [comment]
I'm with Dmitri on this one. The only type of error harder to debug than a state error is one which fails silently.

**Comment by yogthos** [comment]
It might be better to introduce a new filter called `trim` instead here. The `trim` filter could check the length, and trim if it's greater than desired.

**Comment by ricardojmendez** [comment]
> It might be better to introduce a new filter called trim instead here. The trim filter could check the length, and trim if it's greater than desired.

`truncate` might be a better name, since `trim` has a string-related meaning already.

**Comment by martinzuern** [comment]
Failing silently doesn't seem to be a good idea I feel. Luckily, Selmer makes it easy for you to [plug in your own filters](https://github.com/yogthos/Selmer#filters). 
Personally I'd go for the `{% if s|count >= 5 %}` approach, but in case you really need to catch an exception just add your filter function to Selmer using `add-filter!`.

**Comment by stw** [comment]
Ok, seems like most agree that catching the exception is a bad idea. I'm not sure introducing another filter with almost the same functionality makes sense either. I'd vote for leaving it how it is and closing this request.

Thanks,
Steve

**Comment by yogthos** [comment]
Yeah sounds like using a filter would be the way to go in your case.

**Pull request closed without merging**
