### PR TITLE
Add range filter; allow literals in for tag #274

### PR DESCRIPTION
**Pull request by seancorfield**
This adds a `range` filter with all three arities and documents it in the readme.

It also fixes `for` so it works for a literal value with filters.

### CODE REVIEW

**Comment by seancorfield** [comment]
Sorry, this wasn't fully rebased. It should fix #274 though.

**Comment by yogthos** [comment]
Thanks for a thorough PR with docs and tests. :) Just pushed out 1.12.47 release with the updates.

**Comment by seancorfield** [comment]
Awesome! I'll update `deps.edn` at work and start simplifying some of our code and templates!

**Comment by yogthos** [comment]
Fantastic, and thanks again for spearheading the effort.

**Pull request merged**
