### PR TITLE
Fix Cast error in take/drop filters

### PR DESCRIPTION
**Pull request by SVMBrown**
(Sorry, rookie mistake)

### CODE REVIEW

**Comment by yogthos** [comment]
probably would make sense to add a test actually

**Comment by yogthos** [comment]
I'll get that done

**Comment by SVMBrown** [comment]
I am actually just doing it now!

**Comment by yogthos** [comment]
ok sounds good

**Comment by yogthos** [comment]
also note that the filter doesn't produce a value that renders properly

**Comment by yogthos** [comment]
Ideally, filters should produce something that can be rendered to useful output.

**Comment by yogthos** [comment]
for example, running:

```clojure
(render "{{seq-of-some-sort|take:3}}" {:seq-of-some-sort [:dog :cat :bird :bird :bird :is :the :word]})
```

will output:

```
clojure.lang.LazySeq@ee7ad0d2
```

**Comment by yogthos** [comment]
just pushed a fix for that

**Pull request merged**
