### PR TITLE
Adding ability to set up a custom missing-value handler function via …

### PR DESCRIPTION
**Pull request by casperc**
…'set-missing-value-formatter!'.

### CODE REVIEW

**Comment by casperc** [comment]
Idea and discussion of the subject here: https://github.com/yogthos/Selmer/issues/126#issuecomment-248575287

**Comment by casperc** [comment]
I bumped the version to 1.0.8 in the project, because the current jar version is 1.0.7, but the version in the project.clj was 1.0.6.

Is there some code missing from master for 1.0.7?

**Comment by yogthos** [comment]
Luckily no, it was just the version bump I did for the last release and forgot to check in. The PR looks good to me as well. So, I'll push out a new version with the update then.

**Comment by yogthos** [comment]
And 1.0.8 is up on Clojars, thanks for spearheading this.

**Pull request merged**
